// Code generated by go-bindata.
// sources:
// templates/html/feeds.html
// templates/html/items.html
// DO NOT EDIT!

package html

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesHtmlFeedsHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x3c\x8e\x31\x0a\xc3\x30\x0c\x45\xf7\x9c\xe2\x0f\x1e\x4b\xb4\x17\xd5\x63\x4f\xd0\x0b\xa4\x58\x6e\x0c\x6a\x02\xa9\x3b\x14\xa3\xbb\x17\x47\x24\x9b\x04\x4f\xef\x89\xe7\xfa\xd6\x38\x00\x3c\xcb\x94\xfa\x00\x70\x2d\x55\x25\xde\x45\xd2\x87\xc9\x97\x4e\xd0\x81\xf0\x73\x4d\xbf\x38\x38\xfc\x55\xbf\x6a\x0d\x79\xdd\x10\xca\x05\x21\xe3\x7a\xc3\x36\x2d\x2f\xc1\xb8\x6b\x60\xe6\xb4\x96\xd8\x1a\x42\x1e\x1f\x5d\x0b\x33\x26\x2d\xa7\x40\x96\x74\x92\x74\x88\xf7\xb4\x17\x99\xfc\xdd\x7f\x00\x00\x00\xff\xff\xf5\x74\xac\x9c\xb6\x00\x00\x00")

func templatesHtmlFeedsHtmlBytes() ([]byte, error) {
	return bindataRead(
		_templatesHtmlFeedsHtml,
		"templates/html/feeds.html",
	)
}

func templatesHtmlFeedsHtml() (*asset, error) {
	bytes, err := templatesHtmlFeedsHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/html/feeds.html", size: 182, mode: os.FileMode(420), modTime: time.Unix(1523070717, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesHtmlItemsHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb2\xc9\x28\xc9\xcd\xb1\xe3\x52\x50\xb0\xc9\x48\x4d\x4c\x01\x31\x14\x14\x6c\x4a\x32\x4b\x72\x52\xed\xdc\x52\x53\x53\x8a\x6d\xf4\x21\x1c\x90\x0a\x7d\x98\x12\x9b\xa4\xfc\x94\x4a\x3b\x2e\xb0\x18\x84\x69\xa3\x0f\x31\x07\x10\x00\x00\xff\xff\x9b\xb6\x39\x7c\x4f\x00\x00\x00")

func templatesHtmlItemsHtmlBytes() ([]byte, error) {
	return bindataRead(
		_templatesHtmlItemsHtml,
		"templates/html/items.html",
	)
}

func templatesHtmlItemsHtml() (*asset, error) {
	bytes, err := templatesHtmlItemsHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/html/items.html", size: 79, mode: os.FileMode(420), modTime: time.Unix(1523029383, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/html/feeds.html": templatesHtmlFeedsHtml,
	"templates/html/items.html": templatesHtmlItemsHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"html": &bintree{nil, map[string]*bintree{
			"feeds.html": &bintree{templatesHtmlFeedsHtml, map[string]*bintree{}},
			"items.html": &bintree{templatesHtmlItemsHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

